# Generated by Django 6.0.7 on 2026-09-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id_atractivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('calificacion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Atractivo',
                'verbose_name_plural': 'Atractivos',
            },
        ),
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id_bus', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10)),
                ('numero_unidad', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Autobús',
                'verbose_name_plural': 'Autobuses',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id_parada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='paradas/')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id_recorrido', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=30)),
                ('frecuencia', models.IntegerField(help_text='Frecuencia en minutos')),
                ('hora_inicio', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
                ('duracion_aproximada', models.IntegerField(help_text='Duración en minutos')),
            ],
            options={
                'verbose_name': 'Recorrido',
                'verbose_name_plural': 'Recorridos',
            },
        ),
        migrations.CreateModel(
            name='ParadaAtractivo',
            fields=[
                ('id_parada_atractivo', models.AutoField(primary_key=True, serialize=False)),
                ('id_atractivo', models.ForeignKey(db_column='id_atractivo', on_delete=django.db.models.deletion.CASCADE, to='recorridos.atractivo')),
                ('id_parada', models.ForeignKey(db_column='id_parada', on_delete=django.db.models.deletion.CASCADE, to='recorridos.parada')),
            ],
            options={
                'verbose_name': 'Parada-Atractivo',
                'verbose_name_plural': 'Parada-Atractivos',
            },
        ),
        migrations.CreateModel(
            name='RecorridoParada',
            fields=[
                ('id_recorrido_parada', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('id_parada', models.ForeignKey(db_column='id_parada', on_delete=django.db.models.deletion.CASCADE, to='recorridos.parada')),
                ('id_recorrido', models.ForeignKey(db_column='id_recorrido', on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorrido')),
            ],
            options={
                'verbose_name': 'Recorrido-Parada',
                'verbose_name_plural': 'Recorrido-Paradas',
                'ordering': ['id_recorrido', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('id_bus', models.ForeignKey(db_column='id_bus', on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='recorridos.autobus')),
            ],
            options={
                'verbose_name': 'Reparación',
                'verbose_name_plural': 'Reparaciones',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio_programada', models.DateTimeField()),
                ('fecha_hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('id_bus', models.ForeignKey(db_column='id_bus', on_delete=django.db.models.deletion.CASCADE, to='recorridos.autobus')),
                ('id_recorrido', models.ForeignKey(db_column='id_recorrido', on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorrido')),
                ('legajo_chofer', models.ForeignKey(db_column='legajo_chofer', on_delete=django.db.models.deletion.CASCADE, to='recorridos.chofer')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
    ]
